export const navItems = [
  {
    name: 'Istorijos',
    href: '/istorijos',
  },
  {
    name: 'Fotosesijos',
    href: '/fotosesijos',
  },
  {
    name: 'Apie mane',
    href: '/apie',
  },
  {
    name: 'Kontaktai',
    href: '/kontaktai',
  },
];

export const photoshootList = [
  {
    id: 'nn9kjj50',
    name: 'Weeding!!',
    slug: 'victoria-erik',
    description: 'Weeding!!',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/1.jpg?raw=true',
        alt: '',
        width: 916,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/5.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/3.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/2.jpg?raw=true',
        alt: '',
        width: 957,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/6.jpg?raw=true',
        alt: '',
        width: 1103,
        height: 1292,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/4.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/13.jpg?raw=true',
        alt: '',
        width: 954,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/8.jpg?raw=true',
        alt: '',
        width: 914,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/9.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/10.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/11.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/12.jpg?raw=true',
        alt: '',
        width: 894,
        height: 1292,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/12.jpg?raw=true',
        alt: '',
        width: 966,
        height: 1292,
      },
    ],
  },
  {
    id: 'nn9kjj50',
    name: 'Lukas & Heejin',
    slug: 'lukas-heejin',
    description: 'Meilės nušviesti',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/1.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 1077,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/4.jpg?raw=true',
        alt: '',
        width: 949,
        height: 1292,
      },

      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/2.jpg?raw=true',
        alt: '',
        width: 1123,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/3.jpg?raw=true',
        alt: '',
        width: 1135,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/7.jpg?raw=true',
        alt: '',
        width: 992,
        height: 1292,
      },

      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/5.jpg?raw=true',
        alt: '',
        width: 936,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/6.jpg?raw=true',
        alt: '',
        width: 761,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/9.jpg?raw=true',
        alt: '',
        width: 1016,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/8.jpg?raw=true',
        alt: '',
        width: 926,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/10.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 974,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/11.jpg?raw=true',
        alt: '',
        width: 866,
        height: 1292,
      },
    ],
  },
  {
    id: 'mlg6ps9s0',
    name: 'Mažytės drąsuolės krykštynos',
    slug: 'krykstynos-sausis',
    description: 'Mažytės drąsuolės krykštynos',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/1.jpg?raw=true',
        alt: '',
        width: 940,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/2.jpg?raw=true',
        alt: '',
        width: 940,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/5.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/6.jpg?raw=true',
        alt: '',
        width: 983,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/7.jpg?raw=true',
        alt: '',
        width: 1005,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/8.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/4.jpg?raw=true',
        alt: '',
        width: 950,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/3.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
    ],
  },
  {
    id: 'po5rdj30',
    name: 'Pasivaiksčiojimas smagesnis su rogutėm',
    slug: 'kupcik-seimyna',
    description: 'Pasivaiksčiojimas smagesnis su rogutėm',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/1.jpg?raw=truehttps://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/3.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/13.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/4.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/5.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/6.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/7.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/8.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/9.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/11.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/14.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/16.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'gq56djg0',
    name: 'Vaiva & Mikis',
    slug: 'vaiva-mikis',
    description: 'Vaivos ir Mikio šunybės',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/miki/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 3,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/11.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/13.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'g8o6djg3',
    name: 'Violeta',
    slug: 'violeta',
    description: 'Šaltukas nesukliūdė pasikraut gerom emocijom',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/5.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/7.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/8.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'mmd4n2bl',
    name: 'Karolina & Mantas',
    slug: 'karolina-mantas-rotonda',
    description: 'Žieminis pasivaiksčiojimas ir meškučių medžioklė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/1.jpg?raw=true',
        alt: 'couple walking from side to side in park during winter',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'gt5tdjg0',
    name: 'Loz Banditoz',
    slug: 'loz-banditoz',
    description: 'Išsivarėm motociklus žieminei fotosesijai',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/lumi/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/lumi/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: '8kadvnlh',
    name: 'Young',
    slug: 'young-kauno-eglute',
    description: 'Young ir Kauno eglutė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'ur7m375d',
    name: 'Mini Linkedin fotosesija',
    slug: 'linkedin-photoshoot',
    description: 'Kai reikia atsinaujint LinkedIn nuotrauką',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/erni/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/3.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/2.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
    ],
  },
  {
    id: 'fp45cjfz',
    name: 'Booknieta',
    slug: 'booknieta-photoshoot',
    description: 'Dominika ir jos knygų karalystė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/dom/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/dom/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'an1ea3pv',
    name: 'Kvapni Akimirka',
    slug: 'kvapni-akimirka',
    description:
      'Kvapni akimirka - nišiniai kvepalai jaukiuose automaizeriuose',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/cover.jpg?raw=true',
    types: ['product'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/2.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/7.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/9.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/13.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/16.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/17.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 18,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/18.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/19.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
    ],
  },
  {
    id: 'us8n486e',
    name: 'Glorija',
    slug: 'glorijai-1',
    description: 'Glorijos 1-asis tortadienis',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/glory/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/3.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/5.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/6.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/8.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
];
