export const navItems = [
  {
    name: 'Istorijos',
    href: '/istorijos',
  },
  {
    name: 'Fotosesijos',
    href: '/fotosesijos',
  },
  {
    name: 'Apie mane',
    href: '/apie',
  },
  {
    name: 'Kontaktai',
    href: '/kontaktai',
  },
];

export const photoshootList = [
  {
    id: 'gq56djg0',
    name: 'Vaiva & Mikis',
    slug: 'vaiva-mikis',
    description: 'Vaivos ir Mikio šunybės',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/miki/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 3,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/11.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/13.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'g8o6djg3',
    name: 'Violeta',
    slug: 'violeta',
    description: 'Šaltukas nesukliūdė pasikraut gerom emocijom',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'mmd4n2bl',
    name: 'Karolina & Mantas',
    slug: 'karolina-mantas-rotonda',
    description: 'Žieminis pasivaiksčiojimas ir meškučių medžioklė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/1.jpg?raw=true',
        alt: 'couple walking from side to side in park during winter',
        width: 3,
        height: 4,
      },
    ],
  },
  {
    id: 'gt5tdjg0',
    name: 'Loz Banditoz',
    slug: 'loz-banditoz',
    description: 'Išsivarėm motociklus žieminei fotosesijai',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/lumi/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/lumi/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: '8kadvnlh',
    name: 'Young',
    slug: 'young-kauno-eglute',
    description: 'Young ir Kauno eglutė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'ur7m375d',
    name: 'Ernestas',
    slug: 'linkedin-photoshoot',
    description: 'Kai reikia atsinaujint LinkedIn nuotrauką',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/erni/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/3.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/2.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
    ],
  },
  {
    id: 'fp45cjfz',
    name: 'Booknieta',
    slug: 'booknieta-photoshoot',
    description: 'Dominika ir jos knygų karalystė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/dom/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/dom/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'an1ea3pv',
    name: 'Kvapni Akimirka',
    slug: 'kvapni-akimirka',
    description:
      'Kvapni akimirka - nišiniai kvepalai jaukiuose automaizeriuose',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/cover.jpg?raw=true',
    types: ['product'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/2.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/7.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/9.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/13.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/16.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/17.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 18,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/18.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/19.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
    ],
  },
  {
    id: 'us8n486e',
    name: 'Glorija',
    slug: 'glorijai-1',
    description: 'Glorijos 1-asis tortadienis',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/glory/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/3.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/5.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/6.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/8.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
];
