export const navItems = [
  {
    name: 'Istorijos',
    href: '/istorijos',
  },
  {
    name: 'Paslaugos',
    href: '/fotosesijos',
  },
  {
    name: 'Apie mane',
    href: '/apie',
  },
  {
    name: 'Kontaktai',
    href: '/kontaktai',
  },
];

export const propsList = [
  {
    name: 'Juoda antkaklė su gėle',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/juoda-gele-1.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/juoda-gele.jpg?raw=true',
      },
    ],
    types: ['accessories'],
  },
  {
    name: 'Šampano taurės',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/taure-3.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/taure-2.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/taure-1.jpg?raw=true',
      },
    ],
    types: ['dishes'],
  },
  {
    name: 'Baltas Instax fotoaparatas',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/baltas-instax.jpg?raw=true',
      },
    ],
    types: ['objects'],
  },
  {
    name: 'Žydras Instax fotoaparatas',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/zydras-instax.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/zydras-instax-2.jpg?raw=true',
      },
    ],
    types: ['objects'],
  },
  {
    name: 'Rožiniai akiniai',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/akiniai-1.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/akiniai-2.jpg?raw=true',
      },
    ],
    types: ['accessories'],
  },
  {
    name: 'Medinė tortinė',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/medine-tortine-6.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/medine-tortine-7.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/medine-tortine-8.jpg?raw=true',
      },
    ],
    types: ['dishes'],
  },
  {
    name: 'Vyno taurės',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/vyno-taure-2.jpg?raw=true',
      },
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/vyno-taure-1.jpg?raw=true',
      },
    ],
    types: ['dishes'],
  },
  {
    name: 'Baltos tulpės (dirbtinės)',
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/rekvizitai/tulpes.jpg?raw=true',
      },
    ],
    types: ['objects'],
  },
];

export const photoshootList = [
  {
    id: 'ps43r5',
    name: 'Penktadienio vakaras kitaip',
    slug: 'karolina-darius',
    description: 'Penktadienio vakaras kitaip',
    date: '2024-03-01',
    description1:
      'Penktadienio vakarą Karolina ir Darius nusprendė pralesiti kitaip.',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 0,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/cover.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 20,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/20.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/1.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/3.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/5.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/9.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 1059,
      },
      {
        id: 22,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/22.jpg?raw=true',
        alt: '',
        width: 878,
        height: 1292,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/15.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/11.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 595,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/7.jpg?raw=true',
        alt: '',
        width: 1182,
        height: 1292,
      },
      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/19.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/10.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/8.jpg?raw=true',
        alt: '',
        width: 1126,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/2.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/13.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/6.jpg?raw=true',
        alt: '',
        width: 1031,
        height: 1292,
      },
      {
        id: 18,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/18.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/17.jpg?raw=true',
        alt: '',
        width: 929,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/12.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/14.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 23,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/23.jpg?raw=true',
        alt: '',
        width: 1283,
        height: 1292,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/03-01-karo-braz/smalled/16.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
    ],
  },
  {
    id: 'ka03op',
    name: 'Heels Queens vakarėlis',
    slug: 'heels-queens-vakarelis',
    description: 'Heels Queens vakarėlis',
    date: '2024-02-10',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/cover.jpg?raw=true',
    types: ['personal', 'events'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/1.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/17.jpg?raw=true',
        alt: '',
        width: 877,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/5.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 900,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/13.jpg?raw=true',
        alt: '',
        width: 848,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/10.jpg?raw=true',
        alt: '',
        width: 882,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/2.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 882,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/6.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/9.jpg?raw=true',
        alt: '',
        width: 888,
        height: 1292,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/4.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 983,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/16.jpg?raw=true',
        alt: '',
        width: 1025,
        height: 1292,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/14.jpg?raw=true',
        alt: '',
        width: 940,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/3.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 937,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/11.jpg?raw=true',
        alt: '',
        width: 916,
        height: 1292,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/15.jpg?raw=true',
        alt: '',
        width: 976,
        height: 1292,
      },
      {
        id: 20,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/20.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 929,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/12.jpg?raw=true',
        alt: '',
        width: 972,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/8.jpg?raw=true',
        alt: '',
        width: 956,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-10-heels/7.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 774,
      },
    ],
  },
  {
    id: 'ka03op',
    name: 'Popietė su Karolina',
    slug: 'karolina-brazzi',
    description: 'Popietė su Karolina',
    date: '2024-02-05',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/1.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/1.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/11.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/6.jpg?raw=true',
        alt: '',
        width: 998,
        height: 1292,
      },

      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/8.jpg?raw=true',
        alt: '',
        width: 888,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/7.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/3.jpg?raw=true',
        alt: '',
        width: 957,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/10.jpg?raw=true',
        alt: '',
        width: 888,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/5.jpg?raw=true',
        alt: '',
        width: 881,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/02-05-karo-braz/smalled/9.jpg?raw=true',
        alt: '',
        width: 863,
        height: 1292,
      },
    ],
  },
  {
    id: 'nn9kjj50',
    name: 'Vestuvės žiema taip pat gali būt labai šiltos',
    slug: 'victoria-erik',
    date: '2024-01-27',
    description: 'Vestuvės žiema taip pat gali būt labai šiltos',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/cover-3.jpg?raw=true',
    types: ['couple', 'wedding'],
    pictures: [
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/17.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/15.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/3.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/2.jpg?raw=true',
        alt: '',
        width: 957,
        height: 1292,
      },
      {
        id: 27,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/27.jpg?raw=true',
        alt: '',
        width: 829,
        height: 1292,
      },

      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/4.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/1.jpg?raw=true',
        alt: '',
        width: 916,
        height: 1292,
      },
      {
        id: 35,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/35.jpg?raw=true',
        alt: '',
        width: 954,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/8.jpg?raw=true',
        alt: '',
        width: 914,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/9.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/10.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },

      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/14.jpg?raw=true',
        alt: '',
        width: 966,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/12.jpg?raw=true',
        alt: '',
        width: 894,
        height: 1292,
      },
      {
        id: 23,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/23.jpg?raw=true',
        alt: '',
        width: 919,
        height: 1292,
      },

      {
        id: 18,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/18.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/19.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 20,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/20.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 21,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/21.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 26,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/26.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/6.jpg?raw=true',
        alt: '',
        width: 1103,
        height: 1292,
      },
      {
        id: 29,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/29.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 28,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/28.jpg?raw=true',
        alt: '',
        width: 1000,
        height: 1292,
      },
      {
        id: 30,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/30.jpg?raw=true',
        alt: '',
        width: 1215,
        height: 1292,
      },
      {
        id: 32,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/32.jpg?raw=true',
        alt: '',
        width: 906,
        height: 1292,
      },
      {
        id: 31,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/31.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 0,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/cover-2.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 34,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-27-vest/smalled/34.jpg?raw=true',
        alt: '',
        width: 1077,
        height: 1292,
      },
    ],
  },
  {
    id: 'nn9kjj50',
    name: 'Lukas & Heejin',
    slug: 'lukas-heejin',
    date: '2024-01-21',
    description: 'Meilės nušviesti',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/cover.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/1.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 1077,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/4.jpg?raw=true',
        alt: '',
        width: 912,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/2.jpg?raw=true',
        alt: '',
        width: 1123,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/12.jpg?raw=true',
        alt: '',
        width: 1029,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/7.jpg?raw=true',
        alt: '',
        width: 992,
        height: 1292,
      },

      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/5.jpg?raw=true',
        alt: '',
        width: 936,
        height: 1292,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/14.jpg?raw=true',
        alt: '',
        width: 986,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/9.jpg?raw=true',
        alt: '',
        width: 1016,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/8.jpg?raw=true',
        alt: '',
        width: 926,
        height: 1292,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/10.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 974,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/11.jpg?raw=true',
        alt: '',
        width: 866,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/3.jpg?raw=true',
        alt: '',
        width: 1135,
        height: 1292,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/13.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 1063,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/15.jpg?raw=true',
        alt: '',
        width: 1153,
        height: 1292,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-21-andr/smalled/16.jpg?raw=true',
        alt: '',
        width: 1077,
        height: 1292,
      },
    ],
  },
  {
    id: 'mlg6ps9s0',
    name: 'Mažytės drąsuolės krykštynos',
    slug: 'krykstynos-sausis',
    description: 'Mažytės drąsuolės krykštynos',
    date: '2024-02-20',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/1.jpg?raw=true',
        alt: '',
        width: 940,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/2.jpg?raw=true',
        alt: '',
        width: 940,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/5.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/6.jpg?raw=true',
        alt: '',
        width: 983,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/7.jpg?raw=true',
        alt: '',
        width: 1005,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/8.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/4.jpg?raw=true',
        alt: '',
        width: 950,
        height: 1292,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/9.jpg?raw=true',
        alt: '',
        width: 827,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/3.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/10.jpg?raw=true',
        alt: '',
        width: 961,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/12.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/13.jpg?raw=true',
        alt: '',
        width: 1292,
        height: 861,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/14.jpg?raw=true',
        alt: '',
        width: 901,
        height: 1292,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/15.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-20-kry/smalled/16.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
    ],
  },
  {
    id: 'po5rdj30',
    name: 'Pasivaiksčiojimas smagesnis su rogutėm',
    slug: 'kupcik-seimyna',
    description: 'Pasivaiksčiojimas smagesnis su rogutėm',
    date: '2024-01-14',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/1.jpg?raw=truehttps://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/3.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/13.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/4.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/5.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/6.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/7.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/8.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/9.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/11.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/14.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/16.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/17.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },

      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/19.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 20,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/20.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 21,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/21.jpg?raw=true',
        alt: '',
        width: 985,
        height: 1292,
      },
      {
        id: 23,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/23.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 22,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/22.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 32,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/32.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 24,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/24.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 31,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/31.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 25,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/25.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 29,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/29.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 26,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/26.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 28,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/28.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 30,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/30.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 27,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-14-graz/small/27.jpg?raw=true',
        alt: '',
        width: 1034,
        height: 1292,
      },
    ],
  },
  {
    id: 'gq56djg0',
    name: 'Vaiva & Mikis',
    slug: 'vaiva-mikis',
    description: 'Vaivos ir Mikio šunybės',
    date: '2023-12-29',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/miki/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 3,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/11.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/13.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/miki/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'g8o6djg3',
    name: 'Violeta',
    slug: 'violeta',
    date: '2024-01-07',
    description: 'Šaltukas nesukliūdė pasikraut gerom emocijom',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/5.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/7.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2024/01-07-vio/smalled/8.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'mmd4n2bl',
    name: 'Karolina & Mantas',
    slug: 'karolina-mantas-rotonda',
    description: 'Žieminis pasivaiksčiojimas ir meškučių medžioklė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/cover-2.jpg?raw=true',
    types: ['couple'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/1.jpg?raw=true',
        alt: 'couple walking from side to side in park during winter',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/6.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/12.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/13.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/7.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/3.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/14.jpg?raw=true',
        alt: '',
        width: 895,
        height: 1292,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/rotonda/4.jpg?raw=true',
        alt: '',
        width: 1272,
        height: 1292,
      },
    ],
  },
  {
    id: 'gt5tdjg0',
    name: 'Loz Banditoz',
    slug: 'loz-banditoz',
    description: 'Išsivarėm motociklus žieminei fotosesijai',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/lumi/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/lumi/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: '8kadvnlh',
    name: 'Young',
    slug: 'young-kauno-eglute',
    description: 'Kauno Kalėdinis atvirukas',
    date: '2023-12-02',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/4.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/7.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/2.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/6.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/3.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/5.jpg?raw=true',
        alt: '',
        width: 861,
        height: 1292,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kaunas/8.jpg?raw=true',
        alt: '',
        width: 894,
        height: 1292,
      },
    ],
  },
  // {
  //   id: 'ur7m375d',
  //   name: 'Mini Linkedin fotosesija',
  //   slug: 'linkedin-photoshoot',
  //   description: 'Kai reikia atsinaujint LinkedIn nuotrauką',
  //   picture:
  //     'https://github.com/estaniulyte/photos/blob/main/2023/erni/cover.jpg?raw=true',
  //   types: ['personal'],
  //   pictures: [
  //     {
  //       id: 3,
  //       src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/3.jpg?raw=true',
  //       alt: '',
  //       width: 2,
  //       height: 3,
  //     },
  //     {
  //       id: 1,
  //       src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/1.jpg?raw=true',
  //       alt: '',
  //       width: 2,
  //       height: 3,
  //     },
  //     {
  //       id: 2,
  //       src: 'https://github.com/estaniulyte/photos/blob/main/2023/erni/2.jpg?raw=true',
  //       alt: '',
  //       width: 5,
  //       height: 7,
  //     },
  //   ],
  // },
  {
    id: 'fp45cjfz',
    name: 'Booknieta',
    slug: 'booknieta-photoshoot',
    description: 'Dominika ir jos knygų karalystė',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/dom/cover.jpg?raw=true',
    types: ['personal'],
    pictures: [
      {
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/dom/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
  {
    id: 'an1ea3pv',
    name: 'Kvapni Akimirka',
    slug: 'kvapni-akimirka',
    description:
      'Kvapni akimirka - nišiniai kvepalai jaukiuose automaizeriuose',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/cover.jpg?raw=true',
    types: ['product'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/2.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/3.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/5.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/6.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/7.jpg?raw=true',
        alt: '',
        width: 5,
        height: 7,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/8.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/9.jpg?raw=true',
        alt: '',
        width: 3,
        height: 2,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 12,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/12.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 13,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/13.jpg?raw=true',
        alt: '',
        width: 5,
        height: 4,
      },
      {
        id: 14,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/14.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 15,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/15.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 16,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/16.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 17,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/17.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 18,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/18.jpg?raw=true',
        alt: '',
        width: 3,
        height: 4,
      },
      {
        id: 19,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/kvapni/19.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
    ],
  },
  {
    id: 'us8n486e',
    name: 'Glorija',
    slug: 'glorijai-1',
    description: 'Glorijos 1-asis tortadienis',
    picture:
      'https://github.com/estaniulyte/photos/blob/main/2023/glory/cover.jpg?raw=true',
    types: ['family'],
    pictures: [
      {
        id: 1,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/1.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 2,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/2.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 3,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/3.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 5,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/5.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 4,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/4.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 6,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/6.jpg?raw=true',
        alt: '',
        width: 5,
        height: 6,
      },
      {
        id: 7,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/7.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 8,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/8.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 9,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/9.jpg?raw=true',
        alt: '',
        width: 4,
        height: 5,
      },
      {
        id: 10,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/10.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
      {
        id: 11,
        src: 'https://github.com/estaniulyte/photos/blob/main/2023/glory/11.jpg?raw=true',
        alt: '',
        width: 2,
        height: 3,
      },
    ],
  },
];
